version: '3'

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.dockerfile
    depends_on:
      - postgres
    ports:
      - 4001:8080
    environment:
      PORT: 8080
    volumes:
      - ./../broker-service:/app

  user-service:
    build: 
      dockerfile: ./../user-service/user-service.dockerfile
      context: ./../user-service
      target: production
    depends_on:
      - postgres
    ports:
      - 4000:8080
    environment:
      PORT: 8080
      GRPC_PORT: 8081
      ENV: development
      API: http://localhost:8080/
      HOST: localhost
      DSN: host=postgres port=5432 user=postgres password=postgres dbname=users sslmode=disable timezone=UTC connect_timeout=20
    volumes:
      - ./../user-service:/app


  postgres:
    image: 'postgres:15.1-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - 5432:5432
    volumes:
      - ./../user-service/sql/users.sql:/docker-entrypoint-initdb.d/create_tables.sql